version: '3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: 'task-manager-db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=mus'
      - 'POSTGRES_PASSWORD=mus'
      - 'POSTGRES_DB=mus-db'